[meta]
name = "SBS 2d Poker Pack"
author = "Screaming Brain Studios"
card_width = 88
card_height = 124
card_vertical_spacing = 0.25

[textures]
back = "Top-Down/Cards/Back - Top Down 88x124.png"
clubs = "Top-Down/Cards/Clubs - Top Down 88x124.png"
hearts = "Top-Down/Cards/Hearts - Top Down 88x124.png"
spades = "Top-Down/Cards/Spades - Top Down 88x124.png"
diamonds = "Top-Down/Cards/Diamonds - Top Down 88x124.png"

[cards]
  [cards.back]
  texture = "back"
  subset = [0, 0, 88, 124]
  
  [cards.clubs]
  texture = "clubs"
  rows = 3
  columns = 5
  cards = ['A', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', '', '']

  [cards.hearts]
  texture = "hearts"
  rows = 3
  columns = 5
  cards = ['A', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', '', '']

  [cards.spades]
  texture = "spades"
  rows = 3
  columns = 5
  cards = ['A', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', '', '']
  
  [cards.diamonds]
  texture = "diamonds"
  rows = 3
  columns = 5
  cards = ['A', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', '', '']

  # individual cards can be changed as follows
  # [cards.5d]
  # texture = "diamonds"
  # rows = 3
  # columns = 5
  # row = 0
  # col = 4