animations = true
fullscreen = false
sfx = true
window_size = [800, 600]

[solitaire]
dealthree = true
timed = true

[textures]
  [textures.background]
  pack = "SBS 2d Poker Pack"
  texture_name = "Default"

  [textures.backs]
  pack = "8Bit Cards"
  texture_name = "Blue"

  [textures.cards]
  pack = "8Bit Cards"
  texture_name = "Default"

[debug]
render_hitboxes = false
render_animation_list = false
seed = 0
