[meta]
name = "Solitaire Cards"
author = "natomarcacini"
card_vertical_spacing = 0.25

[cards]
  [[cards.back]]
  texture = "Standard 52 Cards/solitaire/individuals/card back/card_back.png"
  name = "Default"
  [[cards.back]]
  texture = "Standard 52 Cards/normal_cards/individual/card back/cardBackGreen.png"
  name = "Green"
  [[cards.back]]
  texture = "Standard 52 Cards/normal_cards/individual/card back/cardBackRed.png"
  name = "Red"

  [[cards.clubs]]
  name = "Default"
  path = "Standard 52 Cards/solitaire/individuals/club"
  files = [
    '1_club.png', '2_club.png', '3_club.png', '4_club.png', '5_club.png', '6_club.png',
    '7_club.png', '8_club.png', '9_club.png', '10_club.png', '11_club.png', '12_club.png', '13_club.png'
  ]

  [[cards.hearts]]
  name = "Default"
  path = "Standard 52 Cards/solitaire/individuals/heart"
  files = [
    '1_heart.png', '2_heart.png', '3_heart.png', '4_heart.png', '5_heart.png', '6_heart.png',
    '7_heart.png', '8_heart.png', '9_heart.png', '10_heart.png', '11_heart.png', '12_heart.png', '13_heart.png'
  ]

  [[cards.spades]]
  name = "Default"
  path = "Standard 52 Cards/solitaire/individuals/spade"
  files = [
    '1_spade.png', '2_spade.png', '3_spade.png', '4_spade.png', '5_spade.png', '6_spade.png',
    '7_spade.png', '8_spade.png', '9_spade.png', '10_spade.png', '11_spade.png', '12_spade.png', '13_spade.png'
  ]

  [[cards.diamonds]]
  name = "Default"
  path = "Standard 52 Cards/solitaire/individuals/diamond"
  files = [
    '1_diamond.png', '2_diamond.png', '3_diamond.png', '4_diamond.png', '5_diamond.png', '6_diamond.png',
    '7_diamond.png', '8_diamond.png', '9_diamond.png', '10_diamond.png', '11_diamond.png', '12_diamond.png', '13_diamond.png'
  ]