[meta]
name = "8Bit Cards"
author = "DrawsGood"
card_width = 35
card_height = 47
card_vertical_spacing = 0.3

[[spritesheets]]
name = "spritesheet"
texture = "8BitDeckAssetsSpritesheet.png"
dimensions = [4, 14]

[cards]
  [[cards.back]]
  spritesheet = "spritesheet"
  name = "Red"
  row = 0
  column = 0
  
  [[cards.back]]
  spritesheet = "spritesheet"
  name = "Blue"
  row = 1
  column = 0

  [[cards.clubs]]
  spritesheet = "spritesheet"
  name = "Default"
  row = 1
  cards = ['', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']  

  [[cards.hearts]]
  spritesheet = "spritesheet"
  name = "Default"
  row = 0
  cards = ['', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']

  [[cards.spades]]
  spritesheet = "spritesheet"
  name = "Default"
  row = 3
  cards = ['', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']
  
  [[cards.diamonds]]
  spritesheet = "spritesheet"
  name = "Default"
  row = 2
  cards = ['', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']